version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - zip -r app.zip . # Zip your app for deployment
artifacts:
  files:
    - app.zip
